################################################################################
# Automatically-generated file. Do not edit!
################################################################################

SHELL = cmd.exe

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../driverlib/adi.c \
../driverlib/aon_batmon.c \
../driverlib/aon_event.c \
../driverlib/aon_ioc.c \
../driverlib/aon_rtc.c \
../driverlib/aon_wuc.c \
../driverlib/aux_adc.c \
../driverlib/aux_smph.c \
../driverlib/aux_tdc.c \
../driverlib/aux_timer.c \
../driverlib/aux_wuc.c \
../driverlib/ccfgread.c \
../driverlib/chipinfo.c \
../driverlib/cpu.c \
../driverlib/crypto.c \
../driverlib/ddi.c \
../driverlib/debug.c \
../driverlib/driverlib_release.c \
../driverlib/event.c \
../driverlib/flash.c \
../driverlib/gpio.c \
../driverlib/i2c.c \
../driverlib/i2s.c \
../driverlib/interrupt.c \
../driverlib/ioc.c \
../driverlib/osc.c \
../driverlib/prcm.c \
../driverlib/pwr_ctrl.c \
../driverlib/rfc.c \
../driverlib/setup.c \
../driverlib/setup_rom.c \
../driverlib/smph.c \
../driverlib/ssi.c \
../driverlib/sw_chacha.c \
../driverlib/sw_poly1305-donna.c \
../driverlib/sys_ctrl.c \
../driverlib/systick.c \
../driverlib/timer.c \
../driverlib/trng.c \
../driverlib/uart.c \
../driverlib/udma.c \
../driverlib/vims.c \
../driverlib/watchdog.c 

C_DEPS += \
./driverlib/adi.d \
./driverlib/aon_batmon.d \
./driverlib/aon_event.d \
./driverlib/aon_ioc.d \
./driverlib/aon_rtc.d \
./driverlib/aon_wuc.d \
./driverlib/aux_adc.d \
./driverlib/aux_smph.d \
./driverlib/aux_tdc.d \
./driverlib/aux_timer.d \
./driverlib/aux_wuc.d \
./driverlib/ccfgread.d \
./driverlib/chipinfo.d \
./driverlib/cpu.d \
./driverlib/crypto.d \
./driverlib/ddi.d \
./driverlib/debug.d \
./driverlib/driverlib_release.d \
./driverlib/event.d \
./driverlib/flash.d \
./driverlib/gpio.d \
./driverlib/i2c.d \
./driverlib/i2s.d \
./driverlib/interrupt.d \
./driverlib/ioc.d \
./driverlib/osc.d \
./driverlib/prcm.d \
./driverlib/pwr_ctrl.d \
./driverlib/rfc.d \
./driverlib/setup.d \
./driverlib/setup_rom.d \
./driverlib/smph.d \
./driverlib/ssi.d \
./driverlib/sw_chacha.d \
./driverlib/sw_poly1305-donna.d \
./driverlib/sys_ctrl.d \
./driverlib/systick.d \
./driverlib/timer.d \
./driverlib/trng.d \
./driverlib/uart.d \
./driverlib/udma.d \
./driverlib/vims.d \
./driverlib/watchdog.d 

OBJS += \
./driverlib/adi.obj \
./driverlib/aon_batmon.obj \
./driverlib/aon_event.obj \
./driverlib/aon_ioc.obj \
./driverlib/aon_rtc.obj \
./driverlib/aon_wuc.obj \
./driverlib/aux_adc.obj \
./driverlib/aux_smph.obj \
./driverlib/aux_tdc.obj \
./driverlib/aux_timer.obj \
./driverlib/aux_wuc.obj \
./driverlib/ccfgread.obj \
./driverlib/chipinfo.obj \
./driverlib/cpu.obj \
./driverlib/crypto.obj \
./driverlib/ddi.obj \
./driverlib/debug.obj \
./driverlib/driverlib_release.obj \
./driverlib/event.obj \
./driverlib/flash.obj \
./driverlib/gpio.obj \
./driverlib/i2c.obj \
./driverlib/i2s.obj \
./driverlib/interrupt.obj \
./driverlib/ioc.obj \
./driverlib/osc.obj \
./driverlib/prcm.obj \
./driverlib/pwr_ctrl.obj \
./driverlib/rfc.obj \
./driverlib/setup.obj \
./driverlib/setup_rom.obj \
./driverlib/smph.obj \
./driverlib/ssi.obj \
./driverlib/sw_chacha.obj \
./driverlib/sw_poly1305-donna.obj \
./driverlib/sys_ctrl.obj \
./driverlib/systick.obj \
./driverlib/timer.obj \
./driverlib/trng.obj \
./driverlib/uart.obj \
./driverlib/udma.obj \
./driverlib/vims.obj \
./driverlib/watchdog.obj 

OBJS__QUOTED += \
"driverlib\adi.obj" \
"driverlib\aon_batmon.obj" \
"driverlib\aon_event.obj" \
"driverlib\aon_ioc.obj" \
"driverlib\aon_rtc.obj" \
"driverlib\aon_wuc.obj" \
"driverlib\aux_adc.obj" \
"driverlib\aux_smph.obj" \
"driverlib\aux_tdc.obj" \
"driverlib\aux_timer.obj" \
"driverlib\aux_wuc.obj" \
"driverlib\ccfgread.obj" \
"driverlib\chipinfo.obj" \
"driverlib\cpu.obj" \
"driverlib\crypto.obj" \
"driverlib\ddi.obj" \
"driverlib\debug.obj" \
"driverlib\driverlib_release.obj" \
"driverlib\event.obj" \
"driverlib\flash.obj" \
"driverlib\gpio.obj" \
"driverlib\i2c.obj" \
"driverlib\i2s.obj" \
"driverlib\interrupt.obj" \
"driverlib\ioc.obj" \
"driverlib\osc.obj" \
"driverlib\prcm.obj" \
"driverlib\pwr_ctrl.obj" \
"driverlib\rfc.obj" \
"driverlib\setup.obj" \
"driverlib\setup_rom.obj" \
"driverlib\smph.obj" \
"driverlib\ssi.obj" \
"driverlib\sw_chacha.obj" \
"driverlib\sw_poly1305-donna.obj" \
"driverlib\sys_ctrl.obj" \
"driverlib\systick.obj" \
"driverlib\timer.obj" \
"driverlib\trng.obj" \
"driverlib\uart.obj" \
"driverlib\udma.obj" \
"driverlib\vims.obj" \
"driverlib\watchdog.obj" 

C_DEPS__QUOTED += \
"driverlib\adi.d" \
"driverlib\aon_batmon.d" \
"driverlib\aon_event.d" \
"driverlib\aon_ioc.d" \
"driverlib\aon_rtc.d" \
"driverlib\aon_wuc.d" \
"driverlib\aux_adc.d" \
"driverlib\aux_smph.d" \
"driverlib\aux_tdc.d" \
"driverlib\aux_timer.d" \
"driverlib\aux_wuc.d" \
"driverlib\ccfgread.d" \
"driverlib\chipinfo.d" \
"driverlib\cpu.d" \
"driverlib\crypto.d" \
"driverlib\ddi.d" \
"driverlib\debug.d" \
"driverlib\driverlib_release.d" \
"driverlib\event.d" \
"driverlib\flash.d" \
"driverlib\gpio.d" \
"driverlib\i2c.d" \
"driverlib\i2s.d" \
"driverlib\interrupt.d" \
"driverlib\ioc.d" \
"driverlib\osc.d" \
"driverlib\prcm.d" \
"driverlib\pwr_ctrl.d" \
"driverlib\rfc.d" \
"driverlib\setup.d" \
"driverlib\setup_rom.d" \
"driverlib\smph.d" \
"driverlib\ssi.d" \
"driverlib\sw_chacha.d" \
"driverlib\sw_poly1305-donna.d" \
"driverlib\sys_ctrl.d" \
"driverlib\systick.d" \
"driverlib\timer.d" \
"driverlib\trng.d" \
"driverlib\uart.d" \
"driverlib\udma.d" \
"driverlib\vims.d" \
"driverlib\watchdog.d" 

C_SRCS__QUOTED += \
"../driverlib/adi.c" \
"../driverlib/aon_batmon.c" \
"../driverlib/aon_event.c" \
"../driverlib/aon_ioc.c" \
"../driverlib/aon_rtc.c" \
"../driverlib/aon_wuc.c" \
"../driverlib/aux_adc.c" \
"../driverlib/aux_smph.c" \
"../driverlib/aux_tdc.c" \
"../driverlib/aux_timer.c" \
"../driverlib/aux_wuc.c" \
"../driverlib/ccfgread.c" \
"../driverlib/chipinfo.c" \
"../driverlib/cpu.c" \
"../driverlib/crypto.c" \
"../driverlib/ddi.c" \
"../driverlib/debug.c" \
"../driverlib/driverlib_release.c" \
"../driverlib/event.c" \
"../driverlib/flash.c" \
"../driverlib/gpio.c" \
"../driverlib/i2c.c" \
"../driverlib/i2s.c" \
"../driverlib/interrupt.c" \
"../driverlib/ioc.c" \
"../driverlib/osc.c" \
"../driverlib/prcm.c" \
"../driverlib/pwr_ctrl.c" \
"../driverlib/rfc.c" \
"../driverlib/setup.c" \
"../driverlib/setup_rom.c" \
"../driverlib/smph.c" \
"../driverlib/ssi.c" \
"../driverlib/sw_chacha.c" \
"../driverlib/sw_poly1305-donna.c" \
"../driverlib/sys_ctrl.c" \
"../driverlib/systick.c" \
"../driverlib/timer.c" \
"../driverlib/trng.c" \
"../driverlib/uart.c" \
"../driverlib/udma.c" \
"../driverlib/vims.c" \
"../driverlib/watchdog.c" 


